In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPRegressor
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import r2_score
from scipy.signal import savgol_filter

In [41]:
def average_scores(iterations, Noise_STD):
    '''
    average_error generates a dataframe for each set of scores, averages all the scores from multiple 
    itterations, and returns the average values as series for each set of scores
    
    '''

    rmse_CN_master_list, score_CN_master_list, rmse_Cu_master_list, score_Cu_master_list, rmse_Te_master_list, score_Te_master_list = compile_score_lists(iterations)

    #generate dataframes for each set of scores
    rmse_CN_master_df = pd.DataFrame(rmse_CN_master_list, columns = Noise_STD)
#    print('rmse_CN_master_df')
#    print(rmse_CN_master_df)
    score_CN_master_df = pd.DataFrame(score_CN_master_list, columns = Noise_STD)
#    print('score_CN_master_df')
#    print(score_CN_master_df)
    rmse_Cu_master_df = pd.DataFrame(rmse_Cu_master_list, columns = Noise_STD)
#    print('rmse_Cu_master_df')
#    print(rmse_Cu_master_df)
    score_Cu_master_df = pd.DataFrame(score_Cu_master_list, columns = Noise_STD)
#    print('score_Cu_master_df')
#    print(score_Cu_master_df)
    rmse_Te_master_df = pd.DataFrame(rmse_Te_master_list, columns = Noise_STD)
#    print('rmse_Te_master_df')
#    print(rmse_Te_master_df)
    score_Te_master_df = pd.DataFrame(score_Te_master_list, columns = Noise_STD)
#    print('score_Te_master_df')
#    print(score_Te_master_df)


    #average the data in the dataframes
    average_rmse_CN = rmse_CN_master_df.mean(axis=0)
    average_rmse_CN = average_rmse_CN.rename('rmse_CN')
    average_score_CN = score_CN_master_df.mean(axis=0)
    average_score_CN = average_score_CN.rename('r2_CN')
    average_rmse_Cu = rmse_Cu_master_df.mean(axis=0)
    average_rmse_Cu = average_rmse_Cu.rename('rmse_Cu')
    average_score_Cu = score_Cu_master_df.mean(axis=0)
    average_score_Cu = average_score_Cu.rename('r2_Cu')
    average_rmse_Te = rmse_Te_master_df.mean(axis=0)
    average_rmse_Te = average_rmse_Te.rename('rmse_Te')
    average_score_Te = score_Te_master_df.mean(axis=0)
    average_score_Te = average_score_Te.rename('r2_Te')

#    print(average_rmse_CN, average_score_CN, average_rmse_Cu, average_score_Cu, average_rmse_Te, average_score_Te)

    results_df = pd.concat([average_rmse_CN, average_score_CN, average_rmse_Cu, average_score_Cu, average_rmse_Te, average_score_Te], axis=1)
    return results_df
    
def compile_score_lists(iterations):
    '''
    average_MLP_models itterates through multiple expieriments and compile a masterlist 
    of all data
    '''
    rmse_CN_master_list = []
    score_CN_master_list = []
    rmse_Cu_master_list = []
    score_Cu_master_list = []
    rmse_Te_master_list = []
    score_Te_master_list = []
    
    for i in range(iterations):
        rmse_CN_i_list = [1, 2, 20, 30, 31, 32, 33, 34, 35, 36, 37] #hard code substitute for 'do the thing'
        rmse_CN_master_list.append(rmse_CN_i_list)
        score_CN_i_list = [3, 4, 21, 40, 41, 42, 43, 44, 45, 46, 47]#hard code substitute for 'do the thing'
        score_CN_master_list.append(score_CN_i_list)
        rmse_Cu_i_list = [5, 6, 22, 50, 51, 52, 53, 54, 55, 56, 57]#hard code substitute for 'do the thing'
        rmse_Cu_master_list.append(rmse_Cu_i_list)
        score_Cu_i_list = [7, 8, 23, 60, 61, 62, 63, 64, 65, 66, 67]#hard code substitute for 'do the thing'
        score_Cu_master_list.append(score_Cu_i_list)
        rmse_Te_i_list = [9, 10, 24, 70, 71, 72, 73, 74, 75, 76, 77]#hard code substitute for 'do the thing'
        rmse_Te_master_list.append(rmse_Te_i_list)
        score_Te_i_list = [11, 12, 25, 80, 81, 82, 83, 84, 85, 86, 87]#hard code substitute for 'do the thing'
        score_Te_master_list.append(score_Te_i_list)
        
    return rmse_CN_master_list, score_CN_master_list, rmse_Cu_master_list, score_Cu_master_list, rmse_Te_master_list, score_Te_master_list

In [42]:
iterations = 2
Noise_STD = [0, 0.005, 0.01, 0.015, 0.02, 0.025, 0.03, 0.035, 0.04, 0.045, 0.05]

In [43]:
compiled_score = average_scores(iterations, Noise_STD)
compiled_score

       rmse_CN  r2_CN  rmse_Cu  r2_Cu  rmse_Te  r2_Te
0.000      1.0    3.0      5.0    7.0      9.0   11.0
0.005      2.0    4.0      6.0    8.0     10.0   12.0
0.010     20.0   21.0     22.0   23.0     24.0   25.0
0.015     30.0   40.0     50.0   60.0     70.0   80.0
0.020     31.0   41.0     51.0   61.0     71.0   81.0
0.025     32.0   42.0     52.0   62.0     72.0   82.0
0.030     33.0   43.0     53.0   63.0     73.0   83.0
0.035     34.0   44.0     54.0   64.0     74.0   84.0
0.040     35.0   45.0     55.0   65.0     75.0   85.0
0.045     36.0   46.0     56.0   66.0     76.0   86.0
0.050     37.0   47.0     57.0   67.0     77.0   87.0